// This file is automatically generated. Do not edit it directly.
// SECURITY NOTE: device-id header is added here intentionally — see SECURITY.md §3.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Generate/retrieve a stable per-device UUID used for RLS ownership scoping.
// This runs once at module load time so the same id is attached to every request.
const DEVICE_ID_KEY = 'leantrack_device_id';
const _getOrCreateDeviceId = (): string => {
  try {
    let id = localStorage.getItem(DEVICE_ID_KEY);
    if (!id) {
      id = crypto.randomUUID();
      localStorage.setItem(DEVICE_ID_KEY, id);
    }
    return id;
  } catch {
    return crypto.randomUUID(); // SSR / test fallback
  }
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      // Attached to every PostgREST call so RLS policies can read it via
      // current_setting('request.headers', true)::json ->> 'x-device-id'
      'x-device-id': _getOrCreateDeviceId(),
    },
  },
});